// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPrimaryTags() {
  return window['go']['main']['App']['GetPrimaryTags']();
}

export function GetRootDirectory() {
  return window['go']['main']['App']['GetRootDirectory']();
}

export function GetSecondaryTags(arg1) {
  return window['go']['main']['App']['GetSecondaryTags'](arg1);
}

export function GetVPKFiles() {
  return window['go']['main']['App']['GetVPKFiles']();
}

export function LaunchL4D2() {
  return window['go']['main']['App']['LaunchL4D2']();
}

export function LogError(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogError'](arg1, arg2, arg3);
}

export function MoveWorkshopToAddons(arg1) {
  return window['go']['main']['App']['MoveWorkshopToAddons'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function ScanVPKFiles() {
  return window['go']['main']['App']['ScanVPKFiles']();
}

export function SearchVPKFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchVPKFiles'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetRootDirectory(arg1) {
  return window['go']['main']['App']['SetRootDirectory'](arg1);
}

export function ToggleVPKFile(arg1) {
  return window['go']['main']['App']['ToggleVPKFile'](arg1);
}

export function ValidateDirectory(arg1) {
  return window['go']['main']['App']['ValidateDirectory'](arg1);
}
