// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDiscoverAddons() {
  return window['go']['main']['App']['AutoDiscoverAddons']();
}

export function CancelDownloadTask(arg1) {
  return window['go']['main']['App']['CancelDownloadTask'](arg1);
}

export function CheckConflicts() {
  return window['go']['main']['App']['CheckConflicts']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearCompletedTasks() {
  return window['go']['main']['App']['ClearCompletedTasks']();
}

export function ConnectToServer(arg1) {
  return window['go']['main']['App']['ConnectToServer'](arg1);
}

export function DeleteVPKFile(arg1) {
  return window['go']['main']['App']['DeleteVPKFile'](arg1);
}

export function DeleteVPKFiles(arg1) {
  return window['go']['main']['App']['DeleteVPKFiles'](arg1);
}

export function DoUpdate(arg1) {
  return window['go']['main']['App']['DoUpdate'](arg1);
}

export function ExportServersToFile(arg1) {
  return window['go']['main']['App']['ExportServersToFile'](arg1);
}

export function ExportVPKFilesToZip(arg1) {
  return window['go']['main']['App']['ExportVPKFilesToZip'](arg1);
}

export function ExtractVPKFrom7z(arg1, arg2) {
  return window['go']['main']['App']['ExtractVPKFrom7z'](arg1, arg2);
}

export function ExtractVPKFromArchive(arg1, arg2) {
  return window['go']['main']['App']['ExtractVPKFromArchive'](arg1, arg2);
}

export function ExtractVPKFromRar(arg1, arg2) {
  return window['go']['main']['App']['ExtractVPKFromRar'](arg1, arg2);
}

export function ExtractVPKFromZip(arg1, arg2) {
  return window['go']['main']['App']['ExtractVPKFromZip'](arg1, arg2);
}

export function FetchPlayerList(arg1) {
  return window['go']['main']['App']['FetchPlayerList'](arg1);
}

export function FetchServerInfo(arg1) {
  return window['go']['main']['App']['FetchServerInfo'](arg1);
}

export function FetchWorkshopDetail(arg1) {
  return window['go']['main']['App']['FetchWorkshopDetail'](arg1);
}

export function FetchWorkshopList(arg1) {
  return window['go']['main']['App']['FetchWorkshopList'](arg1);
}

export function ForceExit() {
  return window['go']['main']['App']['ForceExit']();
}

export function GetDownloadTasks() {
  return window['go']['main']['App']['GetDownloadTasks']();
}

export function GetMapName(arg1) {
  return window['go']['main']['App']['GetMapName'](arg1);
}

export function GetMirrors() {
  return window['go']['main']['App']['GetMirrors']();
}

export function GetPrimaryTags() {
  return window['go']['main']['App']['GetPrimaryTags']();
}

export function GetRootDirectory() {
  return window['go']['main']['App']['GetRootDirectory']();
}

export function GetSecondaryTags(arg1) {
  return window['go']['main']['App']['GetSecondaryTags'](arg1);
}

export function GetVPKFiles() {
  return window['go']['main']['App']['GetVPKFiles']();
}

export function GetWorkshopDetails(arg1) {
  return window['go']['main']['App']['GetWorkshopDetails'](arg1);
}

export function HandleFileDrop(arg1) {
  return window['go']['main']['App']['HandleFileDrop'](arg1);
}

export function HasActiveDownloads() {
  return window['go']['main']['App']['HasActiveDownloads']();
}

export function LaunchL4D2() {
  return window['go']['main']['App']['LaunchL4D2']();
}

export function LogError(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogError'](arg1, arg2, arg3);
}

export function MoveWorkshopToAddons(arg1) {
  return window['go']['main']['App']['MoveWorkshopToAddons'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function ParseWorkshopID(arg1) {
  return window['go']['main']['App']['ParseWorkshopID'](arg1);
}

export function RenameVPKFile(arg1, arg2) {
  return window['go']['main']['App']['RenameVPKFile'](arg1, arg2);
}

export function RestartApplication() {
  return window['go']['main']['App']['RestartApplication']();
}

export function RetryDownloadTask(arg1) {
  return window['go']['main']['App']['RetryDownloadTask'](arg1);
}

export function ScanVPKFiles() {
  return window['go']['main']['App']['ScanVPKFiles']();
}

export function SearchVPKFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchVPKFiles'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SetRootDirectory(arg1) {
  return window['go']['main']['App']['SetRootDirectory'](arg1);
}

export function SetVPKTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetVPKTags'](arg1, arg2, arg3);
}

export function StartDownloadTask(arg1, arg2) {
  return window['go']['main']['App']['StartDownloadTask'](arg1, arg2);
}

export function ToggleVPKFile(arg1) {
  return window['go']['main']['App']['ToggleVPKFile'](arg1);
}

export function ToggleVPKVisibility(arg1) {
  return window['go']['main']['App']['ToggleVPKVisibility'](arg1);
}

export function ValidateDirectory(arg1) {
  return window['go']['main']['App']['ValidateDirectory'](arg1);
}
