// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {parser} from '../models';

export function AutoDiscoverAddons():Promise<string>;

export function CancelDownloadTask(arg1:string):Promise<void>;

export function CheckConflicts():Promise<main.ConflictResult>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ClearCompletedTasks():Promise<void>;

export function ConnectToServer(arg1:string):Promise<void>;

export function DeleteVPKFile(arg1:string):Promise<void>;

export function DeleteVPKFiles(arg1:Array<string>):Promise<void>;

export function DoUpdate(arg1:string):Promise<string>;

export function ExportServersToFile(arg1:string):Promise<string>;

export function ExportVPKFilesToZip(arg1:Array<string>):Promise<string>;

export function ExtractVPKFrom7z(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromArchive(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromRar(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromZip(arg1:string,arg2:string):Promise<void>;

export function FetchPlayerList(arg1:string):Promise<Array<main.PlayerInfo>>;

export function FetchServerInfo(arg1:string):Promise<main.ServerInfo>;

export function FetchWorkshopDetail(arg1:string):Promise<main.WorkshopItemDetail>;

export function FetchWorkshopList(arg1:main.WorkshopQueryOptions):Promise<main.WorkshopListResult>;

export function ForceExit():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetCurrentBestIP():Promise<string>;

export function GetDownloadTasks():Promise<Array<main.DownloadTask>>;

export function GetMapName(arg1:string):Promise<string>;

export function GetMirrors():Promise<Array<string>>;

export function GetModRotation():Promise<main.RotationConfig>;

export function GetPrimaryTags():Promise<Array<string>>;

export function GetRootDirectory():Promise<string>;

export function GetSecondaryTags(arg1:string):Promise<Array<string>>;

export function GetVPKFiles():Promise<Array<parser.VPKFile>>;

export function GetVPKPreviewImage(arg1:string):Promise<string>;

export function GetWorkshopDetails(arg1:string):Promise<Array<main.WorkshopFileDetails>>;

export function GetWorkshopPreferredIP():Promise<boolean>;

export function HandleFileDrop(arg1:Array<string>):Promise<void>;

export function HasActiveDownloads():Promise<boolean>;

export function IsSelectingIP():Promise<boolean>;

export function LaunchL4D2():Promise<void>;

export function LogError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveWorkshopToAddons(arg1:string):Promise<void>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function ParseWorkshopID(arg1:string):Promise<string>;

export function RenameVPKFile(arg1:string,arg2:string):Promise<string>;

export function RestartApplication():Promise<void>;

export function RetryDownloadTask(arg1:string):Promise<void>;

export function RotateMods():Promise<void>;

export function ScanVPKFiles():Promise<void>;

export function SearchVPKFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<parser.VPKFile>>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SetModRotation(arg1:main.RotationConfig):Promise<void>;

export function SetRootDirectory(arg1:string):Promise<void>;

export function SetVPKTags(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetWorkshopPreferredIP(arg1:boolean):Promise<void>;

export function StartDownloadTask(arg1:main.WorkshopFileDetails,arg2:boolean):Promise<string>;

export function ToggleVPKFile(arg1:string):Promise<void>;

export function ToggleVPKVisibility(arg1:string):Promise<string>;

export function ValidateDirectory(arg1:string):Promise<void>;
