// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';

export function GetPrimaryTags():Promise<Array<string>>;

export function GetRootDirectory():Promise<string>;

export function GetSecondaryTags(arg1:string):Promise<Array<string>>;

export function GetVPKFiles():Promise<Array<parser.VPKFile>>;

export function LaunchL4D2():Promise<void>;

export function LogError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveWorkshopToAddons(arg1:string):Promise<void>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function ScanVPKFiles():Promise<void>;

export function SearchVPKFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<parser.VPKFile>>;

export function SelectDirectory():Promise<string>;

export function SetRootDirectory(arg1:string):Promise<void>;

export function ToggleVPKFile(arg1:string):Promise<void>;

export function ValidateDirectory(arg1:string):Promise<void>;
