// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {parser} from '../models';

export function CancelDownloadTask(arg1:string):Promise<void>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ClearCompletedTasks():Promise<void>;

export function ConnectToServer(arg1:string):Promise<void>;

export function DeleteVPKFile(arg1:string):Promise<void>;

export function DeleteVPKFiles(arg1:Array<string>):Promise<void>;

export function DoUpdate():Promise<string>;

export function ExportServersToFile(arg1:string):Promise<string>;

export function ExtractVPKFrom7z(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromArchive(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromRar(arg1:string,arg2:string):Promise<void>;

export function ExtractVPKFromZip(arg1:string,arg2:string):Promise<void>;

export function FetchPlayerList(arg1:string):Promise<Array<main.PlayerInfo>>;

export function FetchServerInfo(arg1:string):Promise<main.ServerInfo>;

export function ForceExit():Promise<void>;

export function GetDownloadTasks():Promise<Array<main.DownloadTask>>;

export function GetPrimaryTags():Promise<Array<string>>;

export function GetRootDirectory():Promise<string>;

export function GetSecondaryTags(arg1:string):Promise<Array<string>>;

export function GetVPKFiles():Promise<Array<parser.VPKFile>>;

export function GetWorkshopDetails(arg1:string):Promise<Array<main.WorkshopFileDetails>>;

export function HandleFileDrop(arg1:Array<string>):Promise<void>;

export function HasActiveDownloads():Promise<boolean>;

export function LaunchL4D2():Promise<void>;

export function LogError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MoveWorkshopToAddons(arg1:string):Promise<void>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function ParseWorkshopID(arg1:string):Promise<string>;

export function RetryDownloadTask(arg1:string):Promise<void>;

export function ScanVPKFiles():Promise<void>;

export function SearchVPKFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<parser.VPKFile>>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SetRootDirectory(arg1:string):Promise<void>;

export function StartDownloadTask(arg1:main.WorkshopFileDetails,arg2:boolean):Promise<string>;

export function ToggleVPKFile(arg1:string):Promise<void>;

export function ValidateDirectory(arg1:string):Promise<void>;
